---
dist: jammy

language: python
python:
  - "3.11"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=5.10.*

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
  - pip install netaddr

script:
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
